export const auth = {
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_ERROR: 'LOG_IN_ERROR',
  LOG_IN_START: 'LOG_IN_START',
  LOG_OUT_USER: 'LOG_OUT_USER',
  SET_CURRENT_TAB: 'SET_CURRENT_TAB',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  SIGN_UP_START: 'SIGN_UP_START',
  UPDATE_LOGGED_IN_USER: 'UPDATE_LOGGED_IN_USER',
};

export const users = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
};

export const userDetails = {
  SET_USER_DETAILS: 'SET_USER_DETAILS',

  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
};

export const devices = {
  SET_DEVICES: 'SET_DEVICES',
  SET_MODEL_FILTER: 'SET_MODEL_FILTER',
  ADD_BRAND_FILTER: 'ADD_BRAND_FILTER',
  REMOVE_BRAND_FILTER: 'REMOVE_BRAND_FILTER',
  ADD_OFFICE_FILTER: 'ADD_OFFICE_FILTER',
  REMOVE_OFFICE_FILTER: 'REMOVE_OFFICE_FILTER',
  SET_SHOW_AVAILABLE: 'SET_SHOW_AVAILABLE',
  SET_SHOW_UNAVAILABLE: 'SET_SHOW_UNAVAILABLE',
  RESET_FILTERS: 'RESET_FILTERS',
  SHOW_BOOK_MODAL: 'SHOW_BOOK_MODAL',
  SET_CURRENT_DATE: 'SET_CURRENT_DATE',
  SET_RETURN_DATE: 'SET_RETURN_DATE',
  SET_RETURN_DATE_ERROR: 'SET_RETURN_DATE_ERROR',
  SET_SELECTED_DEVICE: 'SET_SELECTED_DEVICE',
  SHOW_RESERVE_MODAL: 'SHOW_RESERVE_MODAL',
  SET_RESERVATIONS: 'SET_RESERVATIONS',
  SHOW_RESERVATION_DETAILS: 'SHOW_RESERVATION_DETAILS',
  HIDE_RESERVE_MODAL: 'HIDE_RESERVE_MODAL',
  HIDE_BOOK_MODAL: 'HIDE_BOOK_MODAL',
  HIDE_RESERVATION_DETAILS: 'HIDE_RESERVATION_DETAILS',
  SET_CURRENT_DATE_ERROR: 'SET_CURRENT_DATE_ERROR',
  SHOW_RETURN_MODAL: 'SHOW_RETURN_MODAL',
  HIDE_RETURN_MODAL: 'HIDE_RETURN_MODAL',
  BOOK_START: 'BOOK_START',
  BOOK_SUCCESS: 'BOOK_SUCCESS',
  BOOK_ERROR: 'BOOK_ERROR',
  RESERVE_START: 'RESERVE_START',
  RESERVE_SUCCESS: 'RESERVE_SUCCESS',
  RESERVE_ERROR: 'RESERVE_ERROR',
  FETCH_DEVICE_RESERVATIONS_START: 'FETCH_DEVICE_RESERVATIONS_START',
  FETCH_DEVICE_RESERVATIONS_SUCCESS: 'FETCH_DEVICE_RESERVATIONS_SUCCESS',
  FETCH_DEVICE_RESERVATIONS_ERROR: 'FETCH_DEVICE_RESERVATIONS_ERROR',
  FETCH_DEVICES_START: 'FETCH_DEVICES_START',
  FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
  FETCH_DEVICES_ERROR: 'FETCH_DEVICES_ERROR',
  RETURN_DEVICE_START: 'RETURN_DEVICE_START',
  RETURN_DEVICE_SUCCESS: 'RETURN_DEVICE_SUCCESS',
  RETURN_DEVICE_ERROR: 'RETURN_DEVICE_ERROR',
  CANCEL_RESERVATION_START: 'CANCEL_RESERVATION_START',
  CANCEL_RESERVATION_SUCCESS: 'CANCEL_RESERVATION_SUCCESS',
  CANCEL_RESERVATION_ERROR: 'CANCEL_RESERVATION_ERROR',
  CHECK_IN_START: 'CHECK_IN_START',
  CHECK_IN_SUCCESS: 'CHECK_IN_SUCCESS',
  CHECK_IN_ERROR: 'CHECK_IN_ERROR',
  REMOVE_DEVICE_RESERVATION: 'REMOVE_DEVICE_RESERVATION',
};

export const deviceDetails = {
  SET_DEVICE_DETAILS: 'SET_DEVICE_DETAILS',
  HIDE_LOCATION_MODAL: 'HIDE_LOCATION_MODAL',
  SHOW_LOCATION_MODAL: 'SHOW_LOCATION_MODAL',
  FETCH_DEVICE_START: 'FETCH_DEVICE_START',
  FETCH_DEVICE_ERROR: 'FETCH_DEVICE_ERROR',
  FETCH_DEVICE_SUCCESS: 'FETCH_DEVICE_SUCCESS',
};

export const offices = {
  FETCH_OFFICES_START: 'FETCH_OFFICES_START',
  FETCH_OFFICES_SUCCESS: 'FETCH_OFFICES_SUCCESS',
  FETCH_OFFICES_ERROR: 'FETCH_OFFICES_ERROR',

  CREATE_OFFICE_START: 'CREATE_OFFICE_START',
  CREATE_OFFICE_SUCCESS: 'CREATE_OFFICE_SUCCESS',
  CREATE_OFFICE_ERROR: 'CREATE_OFFICE_ERROR',

  SHOW_ADD_OFFICE_MODAL: 'SHOW_ADD_OFFICE_MODAL',
};

export const officeDetails = {
  FETCH_OFFICE_START: 'FETCH_OFFICE_START',
  FETCH_OFFICE_SUCCESS: 'FETCH_OFFICE_SUCCESS',
  FETCH_OFFICE_ERROR: 'FETCH_OFFICE_ERROR',

  UPDATE_OFFICE_START: 'UPDATE_OFFICE_START',
  UPDATE_OFFICE_SUCCESS: 'UPDATE_OFFICE_SUCCESS',
  UPDATE_OFFICE_ERROR: 'UPDATE_OFFICE_ERROR',
};

export const brands = {
  FETCH_BRANDS_START: 'FETCH_BRANDS_START',
  FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',
  FETCH_BRANDS_ERROR: 'FETCH_BRANDS_ERROR',
};

export const events = {
  FETCH_EVENTS_START: 'FETCH_EVENTS_START',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_ERROR: 'FETCH_EVENTS_ERROR',
  RESET_PAGINATION_INFO: 'RESET_PAGINATION_INFO',
};

