export const auth = {
  SET_USER_INFO: 'SET_USER_INFO',
  LOG_OUT_USER: 'LOG_OUT_USER',
};

export const users = {
  SET_USERS: 'SET_USERS',
};

export const userDetails = {
  SET_USER_DETAILS: 'SET_USER_DETAILS',
};

export const devices = {
  SET_DEVICES: 'SET_DEVICES',
  SET_MODEL_FILTER: 'SET_MODEL_FILTER',
  ADD_BRAND_FILTER: 'ADD_BRAND_FILTER',
  REMOVE_BRAND_FILTER: 'REMOVE_BRAND_FILTER',
  ADD_OFFICE_FILTER: 'ADD_OFFICE_FILTER',
  REMOVE_OFFICE_FILTER: 'REMOVE_OFFICE_FILTER',
  SET_SHOW_AVAILABLE: 'SET_SHOW_AVAILABLE',
  SET_SHOW_UNAVAILABLE: 'SET_SHOW_UNAVAILABLE',
  RESET_FILTERS: 'RESET_FILTERS',
  SHOW_BOOK_MODAL: 'SHOW_BOOK_MODAL',
  SET_CURRENT_DATE: 'SET_CURRENT_DATE',
  SET_RETURN_DATE: 'SET_RETURN_DATE',
  SET_RETURN_DATE_ERROR: 'SET_RETURN_DATE_ERROR',
  SET_SELECTED_DEVICE: 'SET_SELECTED_DEVICE',
  SHOW_RESERVE_MODAL: 'SHOW_RESERVE_MODAL',
  SET_RESERVATIONS: 'SET_RESERVATIONS',
  SHOW_RESERVATION_DETAILS: 'SHOW_RESERVATION_DETAILS',
  HIDE_RESERVE_MODAL: 'HIDE_RESERVE_MODAL',
  HIDE_BOOK_MODAL: 'HIDE_BOOK_MODAL',
  HIDE_RESERVATION_DETAILS: 'HIDE_RESERVATION_DETAILS',
  SET_CURRENT_DATE_ERROR: 'SET_CURRENT_DATE_ERROR',
};

export const deviceDetails = {
  SET_DEVICE_DETAILS: 'SET_DEVICE_DETAILS',
};

export const offices = {
  GET_OFFICES_BEGIN: 'GET_OFFICES_BEGIN',
  GET_OFFICES_SUCCESS: 'GET_OFFICES_SUCCESS',
  GET_OFFICES_ERROR: 'GET_OFFICES_ERROR',

  ADD_OFFICE_BEGIN: 'ADD_OFFICE_BEGIN',
  ADD_OFFICE_SUCCESS: 'ADD_OFFICE_SUCCESS',
  ADD_OFFICE_ERROR: 'ADD_OFFICE_ERROR',

  UPDATE_OFFICE_SUCCESS: 'UPDATE_OFFICE_SUCCESS',

  SHOW_ADD_OFFICE_MODAL: 'SHOW_ADD_OFFICE_MODAL',
};

export const officeDetails = {
  GET_OFFICE_BEGIN: 'GET_OFFICE_BEGIN',
  GET_OFFICE_SUCCESS: 'GET_OFFICE_SUCCESS',
  GET_OFFICE_ERROR: 'GET_OFFICE_ERROR',

  UPDATE_OFFICE_BEGIN: 'UPDATE_OFFICE_BEGIN',
  UPDATE_OFFICE_SUCCESS: 'UPDATE_OFFICE_SUCCESS',
  UPDATE_OFFICE_ERROR: 'UPDATE_OFFICE_ERROR',
};
