export const auth = {
  SET_USER_INFO: 'SET_USER_INFO',
  LOG_OUT_USER: 'LOG_OUT_USER',
};

export const users = {
  SET_USERS: 'SET_USERS',
};

export const userDetails = {
  SET_USER_DETAILS: 'SET_USER_DETAILS',
};

export const devices = {
  SET_DEVICES: 'SET_DEVICES',
  SET_MODEL_FILTER: 'SET_MODEL_FILTER',
  ADD_BRAND_FILTER: 'ADD_BRAND_FILTER',
  REMOVE_BRAND_FILTER: 'REMOVE_BRAND_FILTER',
  ADD_OFFICE_FILTER: 'ADD_OFFICE_FILTER',
  REMOVE_OFFICE_FILTER: 'REMOVE_OFFICE_FILTER',
  SET_SHOW_AVAILABLE: 'SET_SHOW_AVAILABLE',
  SET_SHOW_UNAVAILABLE: 'SET_SHOW_UNAVAILABLE',
  RESET_FILTERS: 'RESET_FILTERS',
  SHOW_BOOK_MODAL: 'SHOW_BOOK_MODAL',
  SET_CURRENT_DATE: 'SET_CURRENT_DATE',
  SET_RETURN_DATE: 'SET_RETURN_DATE',
  SET_RETURN_DATE_ERROR: 'SET_RETURN_DATE_ERROR',
  SET_SELECTED_DEVICE: 'SET_SELECTED_DEVICE',
};
