const BookingEventsList = [
  {
    id: 1,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Wilno',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-01 08:00'),
  },
  {
    id: 2,
    action: 'Check Out',
    device: 'Device id: 1',
    office: 'Wilno',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-02 12:00'),
  },
  {
    id: 3,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Wilno',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-01 08:00'),
  },
  {
    id: 4,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 5,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 6,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 7,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 8,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 9,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 10,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-05 12:00'),
  },
  {
    id: 11,
    action: 'Check In',
    device: 'Device id: 1',
    office: 'Kawns',
    user: 'admin@admin.com',
    datetime: new Date('2018-03-08 20:00:00'),
  },
];

export default BookingEventsList;