const Devices = 
    [
      {
        id: 1,
        brand: 'Apple',
        model: 'iPad Pro 10.5',
        available: true,
        active: true,
        image: 'https://store.storeimages.cdn-apple.com/4974/as-images.apple.com' +
        '/is/image/AppleInc/aos/published/images/i/pa/ipad/cell/ipad-cell-select-spacegray-201703' +
        '?wid=470&hei=556&fmt=png-alpha&.v=1507581905122',
        name: 'Apple iPad Pro 10.5", 256GB',
        custody: 'Name Surname (name.surname@devbridge.com)',
        booked_from: '2018-03-20',
        identification_num: '0000000497',
        serial_num: '123456798ZXJC',
        os: 'macOS High Sierra(version 10.13)',
        group: 'ACC Computers LT',
        subgroup: 'Tablet APPLE',
        description: 'Guest it he tears aware as. Make my no cold of need. ' +
        'He been past in by my hard. Warmly thrown oh he common future. ' +
        'Otherwise concealed favourite frankness on be at dashwoods defective at. ' +
        'Sympathize interested simplicity at do projecting increasing terminated. ' +
        'As edward settle limits at in. ',
        check_in_due: '2018-03-01',
        purchased: '',
        vendor: 'Mark IT',
        tax_rate: '10.0%',
        location: 'Kaunas',
      },
      {
        id: 2,
        brand: 'Sony',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Murrica',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 3,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 4,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 5,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '1',
        available: false,
        active: true,
      },
      {
        id: 6,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },
      {
        id: 7,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 8,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 9,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 10,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 11,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Kaunas',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 12,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },
      {
        id: 13,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Kaunas',
        custody: '',
        available: true,
        active: false,
      },
      {
        id: 14,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },

    ];
      
export default Devices;