const Devices = 
    [
      {
        id: 1,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 2,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 3,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 4,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 5,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: 'John Snow',
        available: false,
        active: true,
      },
      {
        id: 6,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },
      {
        id: 7,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 8,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 9,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Wilno',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 10,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: true,
      },
      {
        id: 11,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Kaunas',
        custody: '',
        available: true,
        active: true,
      },
      {
        id: 12,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },
      {
        id: 13,
        brand: 'Samsung',
        model: 'SM-G930F',
        os: 'Android 7.0',
        location: 'Kaunas',
        custody: '',
        available: true,
        active: false,
      },
      {
        id: 14,
        brand: 'Apple',
        model: 'Ipad Pro 10.5", 256GB',
        os: 'macOS High Sierra (version 10.13)',
        location: 'Kawns',
        custody: 'Bronius',
        available: false,
        active: false,
      },

    ];
      
export default Devices;